global original_files "/Users/miramehta/Documents/TX State Testing Data/Original"
global NCES_files "/Users/miramehta/Documents/NCES District and School Demographics"
global output_files "/Users/miramehta/Documents/TX State Testing Data/Output"
global temp_files "/Users/miramehta/Documents/TX State Testing Data/Temp"

forvalues year = 2012/2024{
	if `year' == 2020{
		continue
	}
//Import Files
	if `year' < 2017{
		use "${output_files}/TX_AssmtData_`year'.dta", clear
	}
	if `year' >= 2017{
		use "${output_files}/TX_AssmtData_`year' - HMH.dta", clear
	}
//Standardize DistNames (set to match 2024)
replace DistName = "A W BROWN LEADERSHIP ACADEMY" if NCESDistrictID == "4800095"
replace DistName = "A+ UNLIMITED POTENTIAL" if NCESDistrictID == "4801453"
replace DistName = "ACADEMY FOR ACADEMIC EXCELLENCE" if NCESDistrictID == "4800093"
replace DistName = "ACADEMY OF ACCELERATED LEARNING INC" if NCESDistrictID == "4800032"
replace DistName = "ACADEMY OF DALLAS" if NCESDistrictID == "4800090"
replace DistName = "ACCELERATED INTERMEDIATE ACADEMY" if NCESDistrictID == "4800192"
replace DistName = "ADVANTAGE ACADEMY" if NCESDistrictID == "4800041"
replace DistName = "ALAMO HEIGHTS ISD" if NCESDistrictID == "4807590"
replace DistName = "ALIEF MONTESSORI COMMUNITY SCHOOL" if NCESDistrictID == "4800035"
replace DistName = "AMBASSADORS PREPARATORY ACADEMY" if NCESDistrictID == "4800284"
replace DistName = "AMIGOS POR VIDA-FRIENDS FOR LIFE PUB CHTR SCH" if NCESDistrictID == "4800113"
replace DistName = "APPLE SPRINGS ISD" if NCESDistrictID == "4808490"
replace DistName = "ARISTOI CLASSICAL ACADEMY" if NCESDistrictID == "4800019"
replace DistName = "ARLINGTON CLASSICS ACADEMY" if NCESDistrictID == "4800158"
replace DistName = "AUSTIN ACHIEVE PUBLIC SCHOOLS" if NCESDistrictID == "4801431"
replace DistName = "AUSTIN DISCOVERY SCHOOL" if NCESDistrictID == "4800265"
replace DistName = "BAKERRIPLEY COMMUNITY SCHOOLS" if NCESDistrictID == "4800240"
replace DistName = "BARBERS HILL ISD" if NCESDistrictID == "4809450"
replace DistName = "BEATRICE MAYES INSTITUTE CHARTER SCHOOL" if NCESDistrictID == "4800190"
replace DistName = "BETTY M CONDRA SCHOOL FOR EDUCATION INNOVATION" if NCESDistrictID == "4801468"
replace DistName = "BEXAR COUNTY ACADEMY" if NCESDistrictID == "4800077"
replace DistName = "BIG SPRINGS CHARTER SCHOOL" if NCESDistrictID == "4800227"
replace DistName = "BLOOM ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4801466"
replace DistName = "BORDEN COUNTY ISD" if NCESDistrictID == "4810860"
replace DistName = "BRAZOS SCHOOL FOR INQUIRY & CREATIVITY" if NCESDistrictID == "4800086"
replace DistName = "BRIDGEWAY PREPARATORY ACADEMY" if NCESDistrictID == "4801462"
replace DistName = "BROOKS COUNTY ISD" if NCESDistrictID == "4811580"
replace DistName = "BURNHAM WOOD CHARTER SCHOOL DISTRICT" if NCESDistrictID == "4800037"
replace DistName = "CALVIN NELMS CHARTER SCHOOLS" if NCESDistrictID == "4800124"
replace DistName = "CARRIZO SPRINGS CISD" if NCESDistrictID == "4812990"
replace DistName = "CENTER POINT ISD" if NCESDistrictID == "4813350"
replace DistName = "CHAPARRAL STAR ACADEMY" if NCESDistrictID == "4800064"
replace DistName = "CHAPEL HILL ACADEMY" if NCESDistrictID == "4801407"
replace DistName = "CHINA SPRING ISD" if NCESDistrictID == "4813960"
replace DistName = "CITYSCAPE SCHOOLS" if NCESDistrictID == "4800288"
replace DistName = "COLLINSVILLE ISD" if NCESDistrictID == "4814580"
replace DistName = "COMO-PICKTON CISD" if NCESDistrictID == "4814880"
replace DistName = "COMPASS ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4801417"
replace DistName = "COMPASS ROSE PUBLIC SCHOOLS" if NCESDistrictID == "4801457"
replace DistName = "COMQUEST ACADEMY" if NCESDistrictID == "4800127"
replace DistName = "COPPERAS COVE ISD" if NCESDistrictID == "4815240"
replace DistName = "CORPUS CHRISTI MONTESSORI SCHOOL" if NCESDistrictID == "4800279"
replace DistName = "COTTON CENTER ISD" if NCESDistrictID == "4815360"
replace DistName = "CRANFILLS GAP ISD" if NCESDistrictID == "4815570"
replace DistName = "CROCKETT COUNTY CONSOLIDATED CSD" if NCESDistrictID == "4815690"
replace DistName = "CROSS PLAINS ISD" if NCESDistrictID == "4815810"
replace DistName = "CRYSTAL CITY ISD" if NCESDistrictID == "4815930"
replace DistName = "CULBERSON COUNTY-ALLAMOORE ISD" if NCESDistrictID == "4815990"
replace DistName = "CUMBERLAND ACADEMY" if NCESDistrictID == "4800034"
replace DistName = "DORAL ACADEMY OF TEXAS" if NCESDistrictID == "4801474"
replace DistName = "DOSS CONSOLIDATED CSD" if NCESDistrictID == "4817400"
replace DistName = "DR M L GARZA-GONZALEZ CHARTER SCHOOL" if NCESDistrictID == "4800025"
replace DistName = "EAGLE MT-SAGINAW ISD" if NCESDistrictID == "4817700"
replace DistName = "EAST BERNARD ISD" if NCESDistrictID == "4817830"
replace DistName = "EAST CENTRAL ISD" if NCESDistrictID == "4817850"
replace DistName = "EAST CHAMBERS ISD" if NCESDistrictID == "4817880"
replace DistName = "EAST FORT WORTH MONTESSORI ACADEMY" if NCESDistrictID == "4800255"
replace DistName = "ECTOR COUNTY ISD" if NCESDistrictID == "4818000"
replace DistName = "EDCOUCH-ELSA ISD" if NCESDistrictID == "4818060"
replace DistName = "EDUCATION CENTER INTERNATIONAL ACADEMY" if NCESDistrictID == "4800186"
replace DistName = "EL PASO LEADERSHIP ACADEMY" if NCESDistrictID == "4801439"
replace DistName = "ELEANOR KOLITZ HEBREW LANGUAGE ACADEMY" if NCESDistrictID == "4801435"
replace DistName = "ELEVATE COLLEGIATE CHARTER SCHOOL" if NCESDistrictID == "4801470"
replace DistName = "ERATH EXCELS ACADEMY INC" if NCESDistrictID == "4800159"
replace DistName = "ESSENCE PREPARATORY CHARTER SCHOOL" if NCESDistrictID == "4801479"
replace DistName = "ETOILE ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4801460"
replace DistName = "EXCELLENCE IN LEADERSHIP ACADEMY" if NCESDistrictID == "4801433"
replace DistName = "FARMERSVILLE ISD" if NCESDistrictID == "4819080"
replace DistName = "FAITH FAMILY ACADEMY" if NCESDistrictID == "4800105"
replace DistName = "FAYETTEVILLE ISD" if NCESDistrictID == "4819140"
replace DistName = "FORT ELLIOTT CISD" if NCESDistrictID == "4811400"
replace DistName = "FORT STOCKTON ISD" if NCESDistrictID == "4820190"
replace DistName = "FORT WORTH ACADEMY OF FINE ARTS" if NCESDistrictID == "4800231"
replace DistName = "FT SAM HOUSTON ISD" if NCESDistrictID == "4820160"
replace DistName = "GATEWAY CHARTER ACADEMY" if NCESDistrictID == "4800184"
replace DistName = "GEORGE GERVIN ACADEMY" if NCESDistrictID == "4800014"
replace DistName = "GEORGE I SANCHEZ CHARTER" if NCESDistrictID == "4800020"
replace DistName = "GLASSCOCK COUNTY ISD" if NCESDistrictID == "4820790"
replace DistName = "GOLDEN RULE CHARTER SCHOOL" if NCESDistrictID == "4800237"
replace DistName = "GOODWATER MONTESSORI SCHOOL" if NCESDistrictID == "4801458"
replace DistName = "GOOSE CREEK CISD" if NCESDistrictID == "4821150"
replace DistName = "GRAND PRAIRIE ISD" if NCESDistrictID == "4821420"
replace DistName = "GRAND SALINE ISD" if NCESDistrictID == "4821450"
replace DistName = "GRANDFALLS-ROYALTY ISD" if NCESDistrictID == "4821480"
replace DistName = "GRANDVIEW-HOPKINS ISD" if NCESDistrictID == "4821560"
replace DistName = "GRAPEVINE-COLLEYVILLE ISD" if NCESDistrictID == "4821660"
replace DistName = "GREAT HEARTS TEXAS" if NCESDistrictID == "4801441"
replace DistName = "GREGORY-PORTLAND ISD" if NCESDistrictID == "4821780"
replace DistName = "HALLETTSVILLE ISD" if NCESDistrictID == "4822120"
replace DistName = "HAMLIN COLLEGIATE ISD" if NCESDistrictID == "4822260"
replace DistName = "HAMSHIRE-FANNET ISD" if NCESDistrictID == "4822320"
replace DistName = "HARDIN-JEFFERSON ISD" if NCESDistrictID == "4822410"
replace DistName = "HARMONY PUBLIC SCHOOLS - CENTRAL TEXAS" if NCESDistrictID == "4800241"
replace DistName = "HARMONY PUBLIC SCHOOLS - HOUSTON NORTH" if NCESDistrictID == "4800274"
replace DistName = "HARMONY PUBLIC SCHOOLS - HOUSTON SOUTH" if NCESDistrictID == "4800210"
replace DistName = "HARMONY PUBLIC SCHOOLS - HOUSTON WEST" if NCESDistrictID == "4801405"
replace DistName = "HARMONY PUBLIC SCHOOLS - NORTH TEXAS" if NCESDistrictID == "4800292"
replace DistName = "HARMONY PUBLIC SCHOOLS - SOUTH TEXAS" if NCESDistrictID == "4800266"
replace DistName = "HARMONY PUBLIC SCHOOLS - WEST TEXAS" if NCESDistrictID == "4800272"
replace DistName = "HERITAGE ACADEMY" if NCESDistrictID == "4800080"
replace DistName = "HORIZON MONTESSORI PUBLIC SCHOOLS" if NCESDistrictID == "4800065"
replace DistName = "HOUSTON CLASSICAL CHARTER SCHOOL" if NCESDistrictID == "4801469"
replace DistName = "HOUSTON GATEWAY ACADEMY INC" if NCESDistrictID == "4800118"
replace DistName = "HUGHES SPRINGS ISD" if NCESDistrictID == "4823850"
replace DistName = "HULL-DAISETTA ISD" if NCESDistrictID == "4823880"
replace DistName = "HURST-EULESS-BEDFORD ISD" if NCESDistrictID == "4824060"
replace DistName = "IDEA PUBLIC SCHOOLS" if NCESDistrictID == "4800211"
replace DistName = "IMAGINE INTERNATIONAL ACADEMY OF NORTH TEXAS" if NCESDistrictID == "4801429"
replace DistName = "INSPIRE ACADEMIES" if NCESDistrictID == "4800053"
replace DistName = "INSPIRED VISION ACADEMY" if NCESDistrictID == "4800204"
replace DistName = "INTERNATIONAL LEADERSHIP OF TEXAS (ILTEXAS)" if NCESDistrictID == "4801440"
replace DistName = "IRAAN-SHEFFIELD COLLEGIATE ISD" if NCESDistrictID == "4824330"
replace DistName = "IRION COUNTY ISD" if NCESDistrictID == "4830360"
replace DistName = "JACKSONVILLE ISD" if NCESDistrictID == "4824590"
replace DistName = "JAYTON-GIRARD ISD" if NCESDistrictID == "4824660"
replace DistName = "JEAN MASSIEU ACADEMY" if NCESDistrictID == "4800098"
replace DistName = "JIM HOGG COUNTY ISD" if NCESDistrictID == "4824750"
replace DistName = "JOHNSON CITY ISD" if NCESDistrictID == "4824840"
replace DistName = "JUBILEE ACADEMIES" if NCESDistrictID == "4800179"
replace DistName = "KATHERINE ANNE PORTER SCHOOL" if NCESDistrictID == "4800132"
replace DistName = "KENEDY COUNTY WIDE CSD" if NCESDistrictID == "4825410"
replace DistName = "KI CHARTER" if NCESDistrictID == "4801447"
replace DistName = "KIPP TEXAS PUBLIC SCHOOLS" if NCESDistrictID == "4800264"
replace DistName = "KNOX CITY-O'BRIEN CISD" if NCESDistrictID == "4825870"
replace DistName = "LA ACADEMIA DE ESTRELLAS" if NCESDistrictID == "4800270"
replace DistName = "LA FE PREPARATORY SCHOOL" if NCESDistrictID == "4800286"
replace DistName = "LAKE GRANBURY ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4801464"
replace DistName = "LEADERSHIP PREP SCHOOL" if NCESDistrictID == "4801420"
replace DistName = "LEGACY PREPARATORY" if NCESDistrictID == "4801428"
replace DistName = "LEGACY SCHOOL OF SPORT SCIENCES" if NCESDistrictID == "4801459"
replace DistName = "LEGACY TRADITIONAL SCHOOLS - TEXAS" if NCESDistrictID == "4800062"
replace DistName = "LEVERETTS CHAPEL ISD" if NCESDistrictID == "4827270"
replace DistName = "LIBERTY HILL ISD" if NCESDistrictID == "4827420"
replace DistName = "LIBERTY-EYLAU ISD" if NCESDistrictID == "4827390"
replace DistName = "LIGHTHOUSE PUBLIC SCHOOLS" if NCESDistrictID == "4800246"
replace DistName = "LINDEN-KILDARE CISD" if NCESDistrictID == "4827540"
replace DistName = "LITTLE CYPRESS-MAURICEVILLE CISD" if NCESDistrictID == "4827690"
replace DistName = "LONE STAR LANGUAGE ACADEMY" if NCESDistrictID == "4801452"
replace DistName = "LONE STAR SCHOOL DISTRICT" if NCESDistrictID == "4801432"
replace DistName = "LOS FRESNOS CISD" if NCESDistrictID == "4828290"
replace DistName = "LUBBOCK-COOPER ISD" if NCESDistrictID == "4815180"
replace DistName = "LUEDERS-AVOCA ISD" if NCESDistrictID == "4828530"
replace DistName = "MADISONVILLE CISD" if NCESDistrictID == "4828710"
replace DistName = "MARBLE FALLS ISD" if NCESDistrictID == "4829010"
replace DistName = "MARTINS MILL ISD" if NCESDistrictID == "4829220"
replace DistName = "MARTINSVILLE ISD" if NCESDistrictID == "4829250"
replace DistName = "MCMULLEN COUNTY ISD" if NCESDistrictID == "4829940"
replace DistName = "MEADOWLAND CHARTER DISTRICT" if NCESDistrictID == "4801404"
replace DistName = "MILLER GROVE ISD" if NCESDistrictID == "4830810"
replace DistName = "MINERAL WELLS ISD" if NCESDistrictID == "4830950"
replace DistName = "MEDINA VALLEY ISD" if NCESDistrictID == "4830060"
replace DistName = "MERIDIAN WORLD SCHOOL LLC" if NCESDistrictID == "4801422"
replace DistName = "MEYERPARK CHARTER" if NCESDistrictID == "4800262"
replace DistName = "MIDLAND ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4800148"
replace DistName = "MILLER GROVE ISD" if NCESDistrictID == "4830810"
replace DistName = "MINERAL WELLS ISD" if NCESDistrictID == "4830950"
replace DistName = "MONAHANS-WICKETT-PYOTE ISD" if NCESDistrictID == "4831170"
replace DistName = "MONTESSORI FOR ALL" if NCESDistrictID == "4801442"
replace DistName = "MOTLEY COUNTY ISD" if NCESDistrictID == "4831500"
replace DistName = "MOUNT ENTERPRISE ISD" if NCESDistrictID == "4831650"
replace DistName = "MOUNT PLEASANT ISD" if NCESDistrictID == "4831760"
replace DistName = "MOUNT VERNON ISD" if NCESDistrictID == "4831770"
replace DistName = "NEW BRAUNFELS ISD" if NCESDistrictID == "4832370"
replace DistName = "NEW FRONTIERS PUBLIC SCHOOLS INC" if NCESDistrictID == "4800061"
replace DistName = "NEW SUMMERFIELD ISD" if NCESDistrictID == "4832610"
replace DistName = "NEWMAN INTERNATIONAL ACADEMY OF ARLINGTON" if NCESDistrictID == "4801421"
replace DistName = "NIXON-SMILEY CISD" if NCESDistrictID == "4832740"
replace DistName = "NORTH HOPKINS ISD" if NCESDistrictID == "4832970"
replace DistName = "NORTH TEXAS COLLEGIATE ACADEMY" if NCESDistrictID == "4800187"
replace DistName = "NOVA ACADEMY SOUTHEAST" if NCESDistrictID == "4800201"
replace DistName = "NYOS CHARTER SCHOOL" if NCESDistrictID == "4800058"
replace DistName = "ODYSSEY ACADEMY INC" if NCESDistrictID == "4800108"
replace DistName = "ORANGE GROVE ISD" if NCESDistrictID == "4833720"
replace DistName = "ORENDA CHARTER SCHOOL" if NCESDistrictID == "4800235"
replace DistName = "PANOLA CHARTER SCHOOL" if NCESDistrictID == "4800213"
replace DistName = "PANTHER CREEK CISD" if NCESDistrictID == "4800007"
replace DistName = "PATTON SPRINGS ISD" if NCESDistrictID == "4834380"
replace DistName = "PECOS-BARSTOW-TOYAH ISD" if NCESDistrictID == "4834550"
replace DistName = "PEGASUS SCHOOL OF LIBERAL ARTS AND SCIENCES" if NCESDistrictID == "4800029"
replace DistName = "PERRIN-WHITT CISD" if NCESDistrictID == "4834630"
replace DistName = "PFLUGERVILLE ISD" if NCESDistrictID == "4834830"
replace DistName = "PHARR-SAN JUAN-ALAMO ISD" if NCESDistrictID == "4834860"
replace DistName = "PINEYWOODS COMMUNITY ACADEMY" if NCESDistrictID == "4800074"
replace DistName = "PIONEER TECHNOLOGY & ARTS ACADEMY" if NCESDistrictID == "4801451"
replace DistName = "PLEASANT GROVE ISD" if NCESDistrictID == "4835130"
replace DistName = "PLEMONS-STINNETT-PHILLIPS CISD" if NCESDistrictID == "4841580"
replace DistName = "POINT ISABEL ISD" if NCESDistrictID == "4835250"
replace DistName = "PORT ARANSAS ISD" if NCESDistrictID == "4835370"
replace DistName = "PORT NECHES-GROVES ISD" if NCESDistrictID == "4835430"
replace DistName = "PRAIRIE VALLEY ISD" if NCESDistrictID == "4835730"
replace DistName = "PRELUDE PREPARATORY CHARTER SCHOOL" if NCESDistrictID == "4801476"
replace DistName = "PREMIER HIGH SCHOOLS" if NCESDistrictID == "4800207"
replace DistName = "PRINGLE-MORSE CISD" if NCESDistrictID == "4835890"
replace DistName = "PRIORITY CHARTER SCHOOLS" if NCESDistrictID == "4800076"
replace DistName = "PROMESA ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4801467"
replace DistName = "RANDOLPH FIELD ISD" if NCESDistrictID == "4836450"
replace DistName = "RAPOPORT ACADEMY PUBLIC SCHOOL" if NCESDistrictID == "4800042"
replace DistName = "RAUL YZAGUIRRE SCHOOLS FOR SUCCESS" if NCESDistrictID == "4800022"
replace DistName = "RAYMONDVILLE ISD" if NCESDistrictID == "4836540"
replace DistName = "REAGAN COUNTY ISD" if NCESDistrictID == "4836570"
replace DistName = "REVE PREPARATORY CHARTER SCHOOL" if NCESDistrictID == "4801465"
replace DistName = "RICHLAND SPRINGS ISD" if NCESDistrictID == "4837080"
replace DistName = "RIO GRANDE CITY GRULLA ISD" if NCESDistrictID == "4837140"
replace DistName = "ROCKETSHIP PUBLIC SCHOOLS" if NCESDistrictID == "4801482"
replace DistName = "ROSCOE COLLEGIATE ISD" if NCESDistrictID == "4837860"
replace DistName = "ROSEBUD-LOTT ISD" if NCESDistrictID == "4837900"
replace DistName = "ROUND TOP-CARMINE ISD" if NCESDistrictID == "4838100"
replace DistName = "ROYAL PUBLIC SCHOOLS" if NCESDistrictID == "4801477"
replace DistName = "S AND S CISD" if NCESDistrictID == "4838400"
replace DistName = "SAM HOUSTON STATE UNIVERSITY CHARTER SCHOOL" if NCESDistrictID == "4801454"
replace DistName = "SAN ANTONIO PREPARATORY SCHOOLS" if NCESDistrictID == "4801472"
replace DistName = "SAN AUGUSTINE ISD" if NCESDistrictID == "4838760"
replace DistName = "SAN ELIZARIO ISD" if NCESDistrictID == "4838850"
replace DistName = "SAN FELIPE-DEL RIO CISD" if NCESDistrictID == "4838900"
replace DistName = "SANFORD-FRITCH ISD" if NCESDistrictID == "4839150"
replace DistName = "SANTA GERTRUDIS ISD" if NCESDistrictID == "4839300"
replace DistName = "SCHERTZ-CIBOLO-U CITY ISD" if NCESDistrictID == "4839480"
replace DistName = "SCURRY-ROSSER ISD" if NCESDistrictID == "4839570"
replace DistName = "SEASHORE CHARTER SCHOOLS" if NCESDistrictID == "4800289"
replace DistName = "SER-NINOS CHARTER SCHOOL" if NCESDistrictID == "4800018"
replace DistName = "SIERRA BLANCA ISD" if NCESDistrictID == "4840200"
replace DistName = "SIVELLS BEND ISD" if NCESDistrictID == "4840380"
replace DistName = "SKIDMORE-TYNAN ISD" if NCESDistrictID == "4840410"
replace DistName = "SOUTH SAN ANTONIO ISD" if NCESDistrictID == "4840680"
replace DistName = "SOUTHWEST PREPARATORY SCHOOL" if NCESDistrictID == "4800063"
replace DistName = "SPRING BRANCH ISD" if NCESDistrictID == "4841100"
replace DistName = "SPRING CREEK ISD" if NCESDistrictID == "4841130"
replace DistName = "SPRINGLAKE-EARTH ISD" if NCESDistrictID == "4841250"
replace DistName = "ST ANTHONY SCHOOL" if NCESDistrictID == "4800248"
replace DistName = "ST MARY'S ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4800177"
replace DistName = "STEP CHARTER SCHOOL" if NCESDistrictID == "4800275"
replace DistName = "STEPHEN F AUSTIN STATE UNIVERSITY CHARTER SCHOOL" if NCESDistrictID == "4801395"
replace DistName = "STEPHENVILLE ISD" if NCESDistrictID == "4841520"
replace DistName = "STERLING CITY ISD" if NCESDistrictID == "4841550"
replace DistName = "SULPHUR BLUFF ISD" if NCESDistrictID == "4841790"
replace DistName = "SULPHUR SPRINGS ISD" if NCESDistrictID == "4841820"
replace DistName = "SUNRAY COLLEGIATE ISD" if NCESDistrictID == "4841910"
replace DistName = "TEKOA ACADEMY OF ACCELERATED STUDIES STEM SCHOOL" if NCESDistrictID == "4800139"
replace DistName = "TEXAS COLLEGE PREPARATORY ACADEMIES" if NCESDistrictID == "4800163"
replace DistName = "TEXAS EMPOWERMENT ACADEMY" if NCESDistrictID == "4800066"
replace DistName = "TEXAS LEADERSHIP PUBLIC SCHOOLS" if NCESDistrictID == "4801409"
replace DistName = "TEXAS PREPARATORY SCHOOL" if NCESDistrictID == "4800194"
replace DistName = "TEXAS SCH FOR THE BLIND & VISUALLY IMPAIRED" if NCESDistrictID == "4800252"
replace DistName = "TEXAS SCHOOL OF THE ARTS" if NCESDistrictID == "4800287"
replace DistName = "THE GATHERING PLACE" if NCESDistrictID == "4801471"
replace DistName = "THE LAWSON ACADEMY" if NCESDistrictID == "4801418"
replace DistName = "THE PRO-VISION ACADEMY" if NCESDistrictID == "4801434"
replace DistName = "THE RHODES SCHOOL FOR PERFORMING ARTS" if NCESDistrictID == "4800283"
replace DistName = "THE VARNETT PUBLIC SCHOOL" if NCESDistrictID == "4800073"
replace DistName = "THREE RIVERS ISD" if NCESDistrictID == "4842690"
replace DistName = "THRIVE CENTER FOR SUCCESS" if NCESDistrictID == "4801481"
replace DistName = "TREETOPS SCHOOL INTERNATIONAL" if NCESDistrictID == "4800068"
replace DistName = "TRINITY BASIN PREPARATORY" if NCESDistrictID == "4800092"
replace DistName = "TRINITY CHARTER SCHOOL" if NCESDistrictID == "4800259"
replace DistName = "TULOSO-MIDWAY ISD" if NCESDistrictID == "4843350"
replace DistName = "TURKEY-QUITAQUE ISD" if NCESDistrictID == "4843400"
replace DistName = "TWO DIMENSIONS PREPARATORY ACADEMY" if NCESDistrictID == "4800069"
replace DistName = "UME PREPARATORY ACADEMY" if NCESDistrictID == "4801425"
replace DistName = "UNIVERSAL ACADEMY" if NCESDistrictID == "4800070"
replace DistName = "UNIVERSITY OF TEXAS ELEMENTARY CHARTER SCHOOL" if NCESDistrictID == "4800251"
replace DistName = "UNIVERSITY OF TEXAS UNIVERSITY CHARTER SCHOOL" if NCESDistrictID == "4800071"
replace DistName = "UPLIFT EDUCATION" if NCESDistrictID == "4800030"
replace DistName = "UT TYLER UNIVERSITY ACADEMY" if NCESDistrictID == "4801427"
replace DistName = "VALERE PUBLIC SCHOOLS" if NCESDistrictID == "4801414"
replace DistName = "VALOR PUBLIC SCHOOLS" if NCESDistrictID == "4801461"
replace DistName = "VANGUARD ACADEMY" if NCESDistrictID == "4800195"
replace DistName = "VILLAGE TECH SCHOOLS" if NCESDistrictID == "4801436"
replace DistName = "VISTA DEL FUTURO CHARTER SCHOOL" if NCESDistrictID == "4801394"
replace DistName = "WALNUT SPRINGS ISD" if NCESDistrictID == "4844520"
replace DistName = "WATER VALLEY ISD" if NCESDistrictID == "4844710"
replace DistName = "WELLMAN-UNION CISD" if NCESDistrictID == "4844910"
replace DistName = "WEST HARDIN COUNTY CISD" if NCESDistrictID == "4845000"
replace DistName = "WEST ORANGE-COVE CISD" if NCESDistrictID == "4845090"
replace DistName = "WHITE SETTLEMENT ISD" if NCESDistrictID == "4845540"
replace DistName = "WICHITA FALLS ISD" if NCESDistrictID == "4845780"
replace DistName = "WESTLAKE ACADEMY CHARTER SCHOOL" if NCESDistrictID == "4800254"
replace DistName = "YELLOWSTONE COLLEGE PREPARATORY" if NCESDistrictID == "4801463"
replace DistName = "YES PREP PUBLIC SCHOOLS INC" if NCESDistrictID == "4800209"
replace DistName = "ZAPATA COUNTY ISD" if NCESDistrictID == "4846710"

	if `year' >= 2022{
		replace DistName = "ROCKPORT-FULTON ISD" if NCESDistrictID == "4808550"
	}

//Organize Variables
order State StateAbbrev StateFips SchYear DataLevel DistName SchName NCESDistrictID StateAssignedDistID NCESSchoolID StateAssignedSchID AssmtName AssmtType Subject GradeLevel StudentGroup StudentGroup_TotalTested StudentSubGroup StudentSubGroup_TotalTested Lev1_count Lev1_percent Lev2_count Lev2_percent Lev3_count Lev3_percent Lev4_count Lev4_percent Lev5_count Lev5_percent AvgScaleScore ProficiencyCriteria ProficientOrAbove_count ProficientOrAbove_percent ParticipationRate Flag_AssmtNameChange Flag_CutScoreChange_ELA Flag_CutScoreChange_math Flag_CutScoreChange_sci Flag_CutScoreChange_soc DistType DistCharter DistLocale SchType SchLevel SchVirtual CountyName CountyCode

sort DataLevel DistName SchName AssmtName Subject GradeLevel StudentGroup StudentSubGroup

//Save & Export
	if `year' >= 2017{
	save "${output_files}/TX_AssmtData_`year' - HMH.dta", replace
	export delimited "${output_files}/TX_AssmtData_`year' - HMH.csv", replace
	drop ApproachingOrAbove_count ApproachingOrAbove_percent
	}
	
	save "${output_files}/TX_AssmtData_`year'.dta", replace
	export delimited "${output_files}/TX_AssmtData_`year'.csv", replace
}
